//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: identity/admin/admin.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Depot_Devtools_Auth_V0_Identity_Admin_AdminClient`, then call methods of this protocol to make API calls.
internal protocol Depot_Devtools_Auth_V0_Identity_Admin_AdminClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Depot_Devtools_Auth_V0_Identity_Admin_AdminClientInterceptorFactoryProtocol? { get }

  func createIdentity(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityResponse>

  func getIdentity(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityResponse>

  func getIdentitiesByAttribute(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeResponse>

  func getIdentities(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesResponse>

  func updateIdentity(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityResponse>

  func deleteIdentity(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityResponse>

  func getAddresses(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesResponse>

  func getAddress(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetAddressRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetAddressResponse>

  func updateAddress(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressResponse>

  func getTraits(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsResponse>

  func updateTraits(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsResponse>

  func getCredentials(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsResponse>

  func updateCredential(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialResponse>

  func getIdentityLoginAttempts(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsResponse>

  func createConnection(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionResponse>

  func getConnections(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsResponse>

  func updateConnection(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionResponse>

  func deleteConnection(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionResponse>

  func createIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaResponse>

  func getIdSchemas(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasResponse>

  func getIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaResponse>

  func getDefaultIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaResponse>

  func updateIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaResponse>

  func markDefaultIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaResponse>

  func deleteIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaResponse>

  func createOAuth2Client(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientResponse>

  func getOAuth2Clients(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsResponse>

  func updateOAuth2Client(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientResponse>

  func deleteOAuth2Client(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientResponse>

  func getEmailsSetup(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupResponse>

  func updateEmailsSetup(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupResponse>

  func getUserBaseStatistics(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsResponse>
}

extension Depot_Devtools_Auth_V0_Identity_Admin_AdminClientProtocol {
  internal var serviceName: String {
    return "depot.devtools.auth.v0.identity.admin.Admin"
  }

  /// Unary call to CreateIdentity
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateIdentity.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createIdentity(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/CreateIdentity",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateIdentityInterceptors() ?? []
    )
  }

  /// Unary call to GetIdentity
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIdentity.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getIdentity(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetIdentity",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIdentityInterceptors() ?? []
    )
  }

  /// Unary call to GetIdentitiesByAttribute
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIdentitiesByAttribute.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getIdentitiesByAttribute(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetIdentitiesByAttribute",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIdentitiesByAttributeInterceptors() ?? []
    )
  }

  /// Unary call to GetIdentities
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIdentities.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getIdentities(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetIdentities",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIdentitiesInterceptors() ?? []
    )
  }

  /// Unary call to UpdateIdentity
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateIdentity.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateIdentity(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/UpdateIdentity",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateIdentityInterceptors() ?? []
    )
  }

  /// Unary call to DeleteIdentity
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteIdentity.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteIdentity(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/DeleteIdentity",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteIdentityInterceptors() ?? []
    )
  }

  /// Unary call to GetAddresses
  ///
  /// - Parameters:
  ///   - request: Request to send to GetAddresses.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getAddresses(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetAddresses",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetAddressesInterceptors() ?? []
    )
  }

  /// Unary call to GetAddress
  ///
  /// - Parameters:
  ///   - request: Request to send to GetAddress.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getAddress(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetAddressRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetAddressResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetAddress",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetAddressInterceptors() ?? []
    )
  }

  /// Unary call to UpdateAddress
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateAddress.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateAddress(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/UpdateAddress",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateAddressInterceptors() ?? []
    )
  }

  /// Unary call to GetTraits
  ///
  /// - Parameters:
  ///   - request: Request to send to GetTraits.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getTraits(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetTraits",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetTraitsInterceptors() ?? []
    )
  }

  /// Unary call to UpdateTraits
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateTraits.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateTraits(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/UpdateTraits",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateTraitsInterceptors() ?? []
    )
  }

  /// Unary call to GetCredentials
  ///
  /// - Parameters:
  ///   - request: Request to send to GetCredentials.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getCredentials(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetCredentials",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCredentialsInterceptors() ?? []
    )
  }

  /// Unary call to UpdateCredential
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateCredential.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateCredential(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/UpdateCredential",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateCredentialInterceptors() ?? []
    )
  }

  /// Unary call to GetIdentityLoginAttempts
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIdentityLoginAttempts.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getIdentityLoginAttempts(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetIdentityLoginAttempts",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIdentityLoginAttemptsInterceptors() ?? []
    )
  }

  /// Unary call to CreateConnection
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateConnection.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createConnection(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/CreateConnection",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateConnectionInterceptors() ?? []
    )
  }

  /// Unary call to GetConnections
  ///
  /// - Parameters:
  ///   - request: Request to send to GetConnections.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getConnections(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetConnections",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetConnectionsInterceptors() ?? []
    )
  }

  /// Unary call to UpdateConnection
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateConnection.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateConnection(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/UpdateConnection",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateConnectionInterceptors() ?? []
    )
  }

  /// Unary call to DeleteConnection
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteConnection.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteConnection(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/DeleteConnection",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteConnectionInterceptors() ?? []
    )
  }

  /// Unary call to CreateIdSchema
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateIdSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/CreateIdSchema",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateIdSchemaInterceptors() ?? []
    )
  }

  /// Unary call to GetIdSchemas
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIdSchemas.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getIdSchemas(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetIdSchemas",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIdSchemasInterceptors() ?? []
    )
  }

  /// Unary call to GetIdSchema
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIdSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetIdSchema",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIdSchemaInterceptors() ?? []
    )
  }

  /// Unary call to GetDefaultIdSchema
  ///
  /// - Parameters:
  ///   - request: Request to send to GetDefaultIdSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getDefaultIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetDefaultIdSchema",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDefaultIdSchemaInterceptors() ?? []
    )
  }

  /// Unary call to UpdateIdSchema
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateIdSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/UpdateIdSchema",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateIdSchemaInterceptors() ?? []
    )
  }

  /// Unary call to MarkDefaultIdSchema
  ///
  /// - Parameters:
  ///   - request: Request to send to MarkDefaultIdSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func markDefaultIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/MarkDefaultIdSchema",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMarkDefaultIdSchemaInterceptors() ?? []
    )
  }

  /// Unary call to DeleteIdSchema
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteIdSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteIdSchema(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/DeleteIdSchema",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteIdSchemaInterceptors() ?? []
    )
  }

  /// Unary call to CreateOAuth2Client
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateOAuth2Client.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createOAuth2Client(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/CreateOAuth2Client",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateOAuth2ClientInterceptors() ?? []
    )
  }

  /// Unary call to GetOAuth2Clients
  ///
  /// - Parameters:
  ///   - request: Request to send to GetOAuth2Clients.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getOAuth2Clients(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetOAuth2Clients",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetOAuth2ClientsInterceptors() ?? []
    )
  }

  /// Unary call to UpdateOAuth2Client
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateOAuth2Client.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateOAuth2Client(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/UpdateOAuth2Client",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateOAuth2ClientInterceptors() ?? []
    )
  }

  /// Unary call to DeleteOAuth2Client
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteOAuth2Client.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteOAuth2Client(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/DeleteOAuth2Client",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteOAuth2ClientInterceptors() ?? []
    )
  }

  /// Unary call to GetEmailsSetup
  ///
  /// - Parameters:
  ///   - request: Request to send to GetEmailsSetup.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getEmailsSetup(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetEmailsSetup",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetEmailsSetupInterceptors() ?? []
    )
  }

  /// Unary call to UpdateEmailsSetup
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateEmailsSetup.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateEmailsSetup(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/UpdateEmailsSetup",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateEmailsSetupInterceptors() ?? []
    )
  }

  /// Unary call to GetUserBaseStatistics
  ///
  /// - Parameters:
  ///   - request: Request to send to GetUserBaseStatistics.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getUserBaseStatistics(
    _ request: Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsResponse> {
    return self.makeUnaryCall(
      path: "/depot.devtools.auth.v0.identity.admin.Admin/GetUserBaseStatistics",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUserBaseStatisticsInterceptors() ?? []
    )
  }
}

internal protocol Depot_Devtools_Auth_V0_Identity_Admin_AdminClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createIdentity'.
  func makeCreateIdentityInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityResponse>]

  /// - Returns: Interceptors to use when invoking 'getIdentity'.
  func makeGetIdentityInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityResponse>]

  /// - Returns: Interceptors to use when invoking 'getIdentitiesByAttribute'.
  func makeGetIdentitiesByAttributeInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeResponse>]

  /// - Returns: Interceptors to use when invoking 'getIdentities'.
  func makeGetIdentitiesInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesResponse>]

  /// - Returns: Interceptors to use when invoking 'updateIdentity'.
  func makeUpdateIdentityInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteIdentity'.
  func makeDeleteIdentityInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityResponse>]

  /// - Returns: Interceptors to use when invoking 'getAddresses'.
  func makeGetAddressesInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesResponse>]

  /// - Returns: Interceptors to use when invoking 'getAddress'.
  func makeGetAddressInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetAddressResponse>]

  /// - Returns: Interceptors to use when invoking 'updateAddress'.
  func makeUpdateAddressInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressResponse>]

  /// - Returns: Interceptors to use when invoking 'getTraits'.
  func makeGetTraitsInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsResponse>]

  /// - Returns: Interceptors to use when invoking 'updateTraits'.
  func makeUpdateTraitsInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsResponse>]

  /// - Returns: Interceptors to use when invoking 'getCredentials'.
  func makeGetCredentialsInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsResponse>]

  /// - Returns: Interceptors to use when invoking 'updateCredential'.
  func makeUpdateCredentialInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialResponse>]

  /// - Returns: Interceptors to use when invoking 'getIdentityLoginAttempts'.
  func makeGetIdentityLoginAttemptsInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsResponse>]

  /// - Returns: Interceptors to use when invoking 'createConnection'.
  func makeCreateConnectionInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionResponse>]

  /// - Returns: Interceptors to use when invoking 'getConnections'.
  func makeGetConnectionsInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsResponse>]

  /// - Returns: Interceptors to use when invoking 'updateConnection'.
  func makeUpdateConnectionInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteConnection'.
  func makeDeleteConnectionInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionResponse>]

  /// - Returns: Interceptors to use when invoking 'createIdSchema'.
  func makeCreateIdSchemaInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaResponse>]

  /// - Returns: Interceptors to use when invoking 'getIdSchemas'.
  func makeGetIdSchemasInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasResponse>]

  /// - Returns: Interceptors to use when invoking 'getIdSchema'.
  func makeGetIdSchemaInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaResponse>]

  /// - Returns: Interceptors to use when invoking 'getDefaultIdSchema'.
  func makeGetDefaultIdSchemaInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaResponse>]

  /// - Returns: Interceptors to use when invoking 'updateIdSchema'.
  func makeUpdateIdSchemaInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaResponse>]

  /// - Returns: Interceptors to use when invoking 'markDefaultIdSchema'.
  func makeMarkDefaultIdSchemaInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteIdSchema'.
  func makeDeleteIdSchemaInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaResponse>]

  /// - Returns: Interceptors to use when invoking 'createOAuth2Client'.
  func makeCreateOAuth2ClientInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientResponse>]

  /// - Returns: Interceptors to use when invoking 'getOAuth2Clients'.
  func makeGetOAuth2ClientsInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsResponse>]

  /// - Returns: Interceptors to use when invoking 'updateOAuth2Client'.
  func makeUpdateOAuth2ClientInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteOAuth2Client'.
  func makeDeleteOAuth2ClientInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientResponse>]

  /// - Returns: Interceptors to use when invoking 'getEmailsSetup'.
  func makeGetEmailsSetupInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupResponse>]

  /// - Returns: Interceptors to use when invoking 'updateEmailsSetup'.
  func makeUpdateEmailsSetupInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupResponse>]

  /// - Returns: Interceptors to use when invoking 'getUserBaseStatistics'.
  func makeGetUserBaseStatisticsInterceptors() -> [ClientInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsResponse>]
}

internal final class Depot_Devtools_Auth_V0_Identity_Admin_AdminClient: Depot_Devtools_Auth_V0_Identity_Admin_AdminClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Depot_Devtools_Auth_V0_Identity_Admin_AdminClientInterceptorFactoryProtocol?

  /// Creates a client for the depot.devtools.auth.v0.identity.admin.Admin service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Depot_Devtools_Auth_V0_Identity_Admin_AdminClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Depot_Devtools_Auth_V0_Identity_Admin_AdminProvider: CallHandlerProvider {
  var interceptors: Depot_Devtools_Auth_V0_Identity_Admin_AdminServerInterceptorFactoryProtocol? { get }

  func createIdentity(request: Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityResponse>

  func getIdentity(request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityResponse>

  func getIdentitiesByAttribute(request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeResponse>

  func getIdentities(request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesResponse>

  func updateIdentity(request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityResponse>

  func deleteIdentity(request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityResponse>

  func getAddresses(request: Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesResponse>

  func getAddress(request: Depot_Devtools_Auth_V0_Identity_Admin_GetAddressRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressResponse>

  func updateAddress(request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressResponse>

  func getTraits(request: Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsResponse>

  func updateTraits(request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsResponse>

  func getCredentials(request: Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsResponse>

  func updateCredential(request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialResponse>

  func getIdentityLoginAttempts(request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsResponse>

  func createConnection(request: Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionResponse>

  func getConnections(request: Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsResponse>

  func updateConnection(request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionResponse>

  func deleteConnection(request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionResponse>

  func createIdSchema(request: Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaResponse>

  func getIdSchemas(request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasResponse>

  func getIdSchema(request: Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaResponse>

  func getDefaultIdSchema(request: Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaResponse>

  func updateIdSchema(request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaResponse>

  func markDefaultIdSchema(request: Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaResponse>

  func deleteIdSchema(request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaResponse>

  func createOAuth2Client(request: Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientResponse>

  func getOAuth2Clients(request: Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsResponse>

  func updateOAuth2Client(request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientResponse>

  func deleteOAuth2Client(request: Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientResponse>

  func getEmailsSetup(request: Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupResponse>

  func updateEmailsSetup(request: Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupResponse>

  func getUserBaseStatistics(request: Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsResponse>
}

extension Depot_Devtools_Auth_V0_Identity_Admin_AdminProvider {
  internal var serviceName: Substring { return "depot.devtools.auth.v0.identity.admin.Admin" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateIdentity":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityResponse>(),
        interceptors: self.interceptors?.makeCreateIdentityInterceptors() ?? [],
        userFunction: self.createIdentity(request:context:)
      )

    case "GetIdentity":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityResponse>(),
        interceptors: self.interceptors?.makeGetIdentityInterceptors() ?? [],
        userFunction: self.getIdentity(request:context:)
      )

    case "GetIdentitiesByAttribute":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeResponse>(),
        interceptors: self.interceptors?.makeGetIdentitiesByAttributeInterceptors() ?? [],
        userFunction: self.getIdentitiesByAttribute(request:context:)
      )

    case "GetIdentities":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesResponse>(),
        interceptors: self.interceptors?.makeGetIdentitiesInterceptors() ?? [],
        userFunction: self.getIdentities(request:context:)
      )

    case "UpdateIdentity":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityResponse>(),
        interceptors: self.interceptors?.makeUpdateIdentityInterceptors() ?? [],
        userFunction: self.updateIdentity(request:context:)
      )

    case "DeleteIdentity":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityResponse>(),
        interceptors: self.interceptors?.makeDeleteIdentityInterceptors() ?? [],
        userFunction: self.deleteIdentity(request:context:)
      )

    case "GetAddresses":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesResponse>(),
        interceptors: self.interceptors?.makeGetAddressesInterceptors() ?? [],
        userFunction: self.getAddresses(request:context:)
      )

    case "GetAddress":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressResponse>(),
        interceptors: self.interceptors?.makeGetAddressInterceptors() ?? [],
        userFunction: self.getAddress(request:context:)
      )

    case "UpdateAddress":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressResponse>(),
        interceptors: self.interceptors?.makeUpdateAddressInterceptors() ?? [],
        userFunction: self.updateAddress(request:context:)
      )

    case "GetTraits":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsResponse>(),
        interceptors: self.interceptors?.makeGetTraitsInterceptors() ?? [],
        userFunction: self.getTraits(request:context:)
      )

    case "UpdateTraits":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsResponse>(),
        interceptors: self.interceptors?.makeUpdateTraitsInterceptors() ?? [],
        userFunction: self.updateTraits(request:context:)
      )

    case "GetCredentials":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsResponse>(),
        interceptors: self.interceptors?.makeGetCredentialsInterceptors() ?? [],
        userFunction: self.getCredentials(request:context:)
      )

    case "UpdateCredential":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialResponse>(),
        interceptors: self.interceptors?.makeUpdateCredentialInterceptors() ?? [],
        userFunction: self.updateCredential(request:context:)
      )

    case "GetIdentityLoginAttempts":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsResponse>(),
        interceptors: self.interceptors?.makeGetIdentityLoginAttemptsInterceptors() ?? [],
        userFunction: self.getIdentityLoginAttempts(request:context:)
      )

    case "CreateConnection":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionResponse>(),
        interceptors: self.interceptors?.makeCreateConnectionInterceptors() ?? [],
        userFunction: self.createConnection(request:context:)
      )

    case "GetConnections":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsResponse>(),
        interceptors: self.interceptors?.makeGetConnectionsInterceptors() ?? [],
        userFunction: self.getConnections(request:context:)
      )

    case "UpdateConnection":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionResponse>(),
        interceptors: self.interceptors?.makeUpdateConnectionInterceptors() ?? [],
        userFunction: self.updateConnection(request:context:)
      )

    case "DeleteConnection":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionResponse>(),
        interceptors: self.interceptors?.makeDeleteConnectionInterceptors() ?? [],
        userFunction: self.deleteConnection(request:context:)
      )

    case "CreateIdSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaResponse>(),
        interceptors: self.interceptors?.makeCreateIdSchemaInterceptors() ?? [],
        userFunction: self.createIdSchema(request:context:)
      )

    case "GetIdSchemas":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasResponse>(),
        interceptors: self.interceptors?.makeGetIdSchemasInterceptors() ?? [],
        userFunction: self.getIdSchemas(request:context:)
      )

    case "GetIdSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaResponse>(),
        interceptors: self.interceptors?.makeGetIdSchemaInterceptors() ?? [],
        userFunction: self.getIdSchema(request:context:)
      )

    case "GetDefaultIdSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaResponse>(),
        interceptors: self.interceptors?.makeGetDefaultIdSchemaInterceptors() ?? [],
        userFunction: self.getDefaultIdSchema(request:context:)
      )

    case "UpdateIdSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaResponse>(),
        interceptors: self.interceptors?.makeUpdateIdSchemaInterceptors() ?? [],
        userFunction: self.updateIdSchema(request:context:)
      )

    case "MarkDefaultIdSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaResponse>(),
        interceptors: self.interceptors?.makeMarkDefaultIdSchemaInterceptors() ?? [],
        userFunction: self.markDefaultIdSchema(request:context:)
      )

    case "DeleteIdSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaResponse>(),
        interceptors: self.interceptors?.makeDeleteIdSchemaInterceptors() ?? [],
        userFunction: self.deleteIdSchema(request:context:)
      )

    case "CreateOAuth2Client":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientResponse>(),
        interceptors: self.interceptors?.makeCreateOAuth2ClientInterceptors() ?? [],
        userFunction: self.createOAuth2Client(request:context:)
      )

    case "GetOAuth2Clients":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsResponse>(),
        interceptors: self.interceptors?.makeGetOAuth2ClientsInterceptors() ?? [],
        userFunction: self.getOAuth2Clients(request:context:)
      )

    case "UpdateOAuth2Client":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientResponse>(),
        interceptors: self.interceptors?.makeUpdateOAuth2ClientInterceptors() ?? [],
        userFunction: self.updateOAuth2Client(request:context:)
      )

    case "DeleteOAuth2Client":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientResponse>(),
        interceptors: self.interceptors?.makeDeleteOAuth2ClientInterceptors() ?? [],
        userFunction: self.deleteOAuth2Client(request:context:)
      )

    case "GetEmailsSetup":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupResponse>(),
        interceptors: self.interceptors?.makeGetEmailsSetupInterceptors() ?? [],
        userFunction: self.getEmailsSetup(request:context:)
      )

    case "UpdateEmailsSetup":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupResponse>(),
        interceptors: self.interceptors?.makeUpdateEmailsSetupInterceptors() ?? [],
        userFunction: self.updateEmailsSetup(request:context:)
      )

    case "GetUserBaseStatistics":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsRequest>(),
        responseSerializer: ProtobufSerializer<Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsResponse>(),
        interceptors: self.interceptors?.makeGetUserBaseStatisticsInterceptors() ?? [],
        userFunction: self.getUserBaseStatistics(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Depot_Devtools_Auth_V0_Identity_Admin_AdminServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'createIdentity'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateIdentityInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateIdentityResponse>]

  /// - Returns: Interceptors to use when handling 'getIdentity'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIdentityInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityResponse>]

  /// - Returns: Interceptors to use when handling 'getIdentitiesByAttribute'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIdentitiesByAttributeInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesByAttributeResponse>]

  /// - Returns: Interceptors to use when handling 'getIdentities'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIdentitiesInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentitiesResponse>]

  /// - Returns: Interceptors to use when handling 'updateIdentity'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateIdentityInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdentityResponse>]

  /// - Returns: Interceptors to use when handling 'deleteIdentity'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteIdentityInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdentityResponse>]

  /// - Returns: Interceptors to use when handling 'getAddresses'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetAddressesInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetAddressesResponse>]

  /// - Returns: Interceptors to use when handling 'getAddress'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetAddressInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetAddressRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetAddressResponse>]

  /// - Returns: Interceptors to use when handling 'updateAddress'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateAddressInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateAddressResponse>]

  /// - Returns: Interceptors to use when handling 'getTraits'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetTraitsInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetTraitsResponse>]

  /// - Returns: Interceptors to use when handling 'updateTraits'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateTraitsInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateTraitsResponse>]

  /// - Returns: Interceptors to use when handling 'getCredentials'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetCredentialsInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetCredentialsResponse>]

  /// - Returns: Interceptors to use when handling 'updateCredential'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateCredentialInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateCredentialResponse>]

  /// - Returns: Interceptors to use when handling 'getIdentityLoginAttempts'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIdentityLoginAttemptsInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdentityLoginAttemptsResponse>]

  /// - Returns: Interceptors to use when handling 'createConnection'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateConnectionInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateConnectionResponse>]

  /// - Returns: Interceptors to use when handling 'getConnections'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetConnectionsInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetConnectionsResponse>]

  /// - Returns: Interceptors to use when handling 'updateConnection'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateConnectionInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateConnectionResponse>]

  /// - Returns: Interceptors to use when handling 'deleteConnection'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteConnectionInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteConnectionResponse>]

  /// - Returns: Interceptors to use when handling 'createIdSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateIdSchemaInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateIdSchemaResponse>]

  /// - Returns: Interceptors to use when handling 'getIdSchemas'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIdSchemasInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemasResponse>]

  /// - Returns: Interceptors to use when handling 'getIdSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIdSchemaInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetIdSchemaResponse>]

  /// - Returns: Interceptors to use when handling 'getDefaultIdSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetDefaultIdSchemaInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetDefaultIdSchemaResponse>]

  /// - Returns: Interceptors to use when handling 'updateIdSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateIdSchemaInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateIdSchemaResponse>]

  /// - Returns: Interceptors to use when handling 'markDefaultIdSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMarkDefaultIdSchemaInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_MarkDefaultIdSchemaResponse>]

  /// - Returns: Interceptors to use when handling 'deleteIdSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteIdSchemaInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteIdSchemaResponse>]

  /// - Returns: Interceptors to use when handling 'createOAuth2Client'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateOAuth2ClientInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_CreateOAuth2ClientResponse>]

  /// - Returns: Interceptors to use when handling 'getOAuth2Clients'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetOAuth2ClientsInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetOAuth2ClientsResponse>]

  /// - Returns: Interceptors to use when handling 'updateOAuth2Client'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateOAuth2ClientInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateOAuth2ClientResponse>]

  /// - Returns: Interceptors to use when handling 'deleteOAuth2Client'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteOAuth2ClientInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientRequest, Depot_Devtools_Auth_V0_Identity_Admin_DeleteOAuth2ClientResponse>]

  /// - Returns: Interceptors to use when handling 'getEmailsSetup'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetEmailsSetupInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetEmailsSetupResponse>]

  /// - Returns: Interceptors to use when handling 'updateEmailsSetup'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateEmailsSetupInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupRequest, Depot_Devtools_Auth_V0_Identity_Admin_UpdateEmailsSetupResponse>]

  /// - Returns: Interceptors to use when handling 'getUserBaseStatistics'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetUserBaseStatisticsInterceptors() -> [ServerInterceptor<Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsRequest, Depot_Devtools_Auth_V0_Identity_Admin_GetUserBaseStatisticsResponse>]
}
